rootProject.name = "Tulip"
include(":libtulip")
include(":libtulip-persistence-api")
include(":libtulip-persistence-inmemory")
include(":libtulip-api")
include(":libtulip-service")
include(":libtulip-ui-api")
include(":libtulip-ui")

include(":app")
include(":app-web-kt")

include(":ksoup")
include(":libtvprovider")
include(":libtvprovider-primewire")
include(":libwebdriver-android")
include(":libtvvideoextractor")
include(":commonutils")
include(":libwebdriver")
include(":libtvprovider-kinox")
include(":libtvprovider-southpark")
include(":libtmdb")
include(":libopensubtitles")
include(":rektor")
