version: 2.1

commands:
  deploy-to-github-pages:
    description: "Deploy files to GitHub pages"
    parameters:
      src:
        type: string
      subdir:
        default: ""
        type: string
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:7a:94:bc:1c:cb:d3:3b:58:9d:a8:1a:fa:e9:e9:4d"
      - run:
          name: "Deploy to GitHub Pages"
          command: |
            cd
            git clone "${GIT_DEPLOY_REPO_URL}"
            mkdir -p "${GIT_DEPLOY_REPO_NAME}/<<parameters.subdir>>"
            cp -r <<parameters.src>> "${GIT_DEPLOY_REPO_NAME}/<<parameters.subdir>>"
            cd "${GIT_DEPLOY_REPO_NAME}/"
            git add .
            git config user.email "${GIT_DEPLOY_EMAIL}"
            git config user.name "${GIT_DEPLOY_NAME}"
            git commit -m "${CIRCLE_SHA1}" && git push || true

jobs:
  web-build:
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      - run:
          name: "Build production JS"
          command: |
            ./gradlew app-web-kt:browserProductionWebpack
      - store_artifacts:
          path: ./app-web-kt/build/distributions
      - persist_to_workspace:
          root: .
          paths:
            - app-web-kt/build/distributions/*
  web-deploy:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - deploy-to-github-pages:
          src: "~/project/app-web-kt/build/distributions/*"
  android-build:
    docker:
      - image: cimg/android:2022.03.1
    steps:
      - checkout
      - run:
          name: "Prepare keystore"
          command: |
            echo "${SIGNING_KEYSTORE}" | base64 -d > "${SIGNING_KEYSTORE_NAME}"
            echo "signing.store.file=${SIGNING_KEYSTORE_NAME}" >> signing.properties
            echo "signing.store.password=${SIGNING_KEYSTORE_PASSWORD}" >> signing.properties
            echo "signing.key.alias=${SIGNING_KEYSTORE_KEY_ALIAS}" >> signing.properties
            echo "signing.key.password=${SIGNING_KEYSTORE_KEY_PASSWORD}" >> signing.properties
      - run:
          name: "Build signed release"
          command: |
            ./gradlew app:assembleRelease
      - store_artifacts:
          path: ./app/build/outputs/apk/release
      - persist_to_workspace:
          root: .
          paths:
            - app/build/outputs/apk/release/*
  android-deploy-fdroid:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "Install F-Droid server"
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EC4632C79C5E0151
            sudo add-apt-repository ppa:fdroid/fdroidserver -y
            sudo apt-get update
            sudo apt-get install fdroidserver
      - run:
          name: "Prepare F-Droid template"
          command: |
            cd app/fdroid/
            mkdir repo/
            cp ~/project/app/build/outputs/apk/release/*.apk repo/
            echo "${SIGNING_KEYSTORE}" | base64 -d > "${SIGNING_KEYSTORE_NAME}"
            echo "keystore: ${SIGNING_KEYSTORE_NAME}" >> config.yml
            echo "keystorepass: ${SIGNING_KEYSTORE_PASSWORD}" >> config.yml
            echo "repo_keyalias: ${SIGNING_KEYSTORE_KEY_ALIAS}" >> config.yml
            echo "keypass: ${SIGNING_KEYSTORE_KEY_PASSWORD}" >> config.yml
            echo "repo_url: ${DEPLOY_PAGE_URL}/fdroid/repo" >> config.yml
      - run:
          name: "Update F-Droid repository"
          command: |
            cd ~/project/app/fdroid/
            fdroid update
      - deploy-to-github-pages:
          src: "~/project/app/fdroid/metadata ~/project/app/fdroid/repo"
          subdir: "fdroid"


workflows:
  web-build-deploy:
    jobs:
      - web-build
      - web-deploy:
          requires:
            - web-build
          filters:
            branches:
              only:
                - main
  android-build-deploy-fdroid:
    jobs:
      - android-build
      - android-deploy-fdroid:
          requires:
            - android-build
          filters:
            branches:
              only:
                - main
